name: Django CI

on:
  push:
    branches:
    - Marioespiro-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Prepare app for deploy
      run: |
        cd backend
        rm settings.py
        cp deploy_settings.py settings.py
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic
        cd ..
        zip -r backend.zip backend
    - name: Copy new app version
      run: |
        sudo apt-get install sshpass
        sshpass -p ${{ secrets.PYANY_PASSWD }} scp /backend.zip ${{ secrets.PYANY_USER }}@ssh.pythonanywhere:/home/${{ secrets.PYANY_USER }}/backend.zip
    - name: Update app in pythonanywhere
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: "ssh.pythonanywhere.com"
        username: ${{ secrets.PYANY_USER }}
        password: ${{ secrets.PYANY_PASSWD }}
        script: |
          chmod -R 777 backend
          rm -rf backend
          source env2/bin/activate
          unzip backend.zip
          cd backend
          pip install -r requirements.txt
    - name: Reload pythonanywhere webapp
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'www.pythonanywhere.com'
        username: ${{ secrets.PYANY_USER }}
        api-token: ${{ secrets.PYANY_TOKEN }}
        domain-name: ${{ secrets.PYANY_DOMAIN }}

