name: Pythonanywhere Auto-Deployment (main)

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Prepare app for deploy
      run: |
        cd backend
        rm settings.py
        cp deploy_main_settings.py settings.py
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic
        cd ..
        cp -r backend main
        zip -r main.zip main
    - name: Copy new app version
      run:  sshpass -p "${{ secrets.PYANY_PASSWD }}" scp -oStrictHostKeyChecking=accept-new main.zip ${{ secrets.PYANY_USER }}@ssh.pythonanywhere.com:/home/${{ secrets.PYANY_USER }}/main.zip
    - name: Update app in pythonanywhere
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: "ssh.pythonanywhere.com"
        username: ${{ secrets.PYANY_USER }}
        password: ${{ secrets.PYANY_PASSWD }}
        script: |
          chmod -R 777 main
          rm -rf main
          source env2/bin/activate
          unzip main.zip
          rm main.zip
          cd main
          pip install -r requirements.txt
    - name: Reload pythonanywhere webapp
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'www.pythonanywhere.com'
        username: ${{ secrets.PYANY_USER }}
        api-token: ${{ secrets.PYANY_TOKEN }}
        domain-name: ${{ secrets.PYANY_DOMAIN }}